products = [
    {
        'id': 1,
        'name': "Radeon RX 6600",
        'images': [
            "/images/1.png",
            "/images/2.png",
            "/images/3.png",
            "/images/4.png",
            "/images/5.png",
        ],
        'brand': "Gigabyte",
        'price': 275,
        'description': "A solid mid-range option for 1080p gaming with good performance at a reasonable price. It uses AMD Radeon RX 6600 architecture and features 8GB of GDDR6 memory.",
        'countInStock': 15,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        'id': 2,
        'name': "GeForce RTX 3060 Ti GAMING X 8G LHR",
        'images': [
            "/images/11.png",
            "/images/12.png",
            "/images/13.png",
            "/images/14.png",
        ],
        'brand': "Asus",
        'price': 454,
        'description': "A powerful choice for 1440p gaming with high frame rates and excellent performance in ray tracing thanks to NVIDIA's DLSS technology and Ampere architecture. This LHR version limits hash rate for cryptocurrency mining.",
        'countInStock': 13,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'id': 3,
        'name': "GeForce RTX 3070 GAMING X TRIO 8192MB ",
        'images': [
            "/images/3.1.png",
            "/images/3.2.png",
            "/images/3.3.png",
            "/images/3.4.png",
        ],
        'brand': "MSI",
        'price': 503,
        'description': "A powerful choice for 1440p gaming with high frame rates and excellent performance in ray tracing thanks to NVIDIA's DLSS technology and Ampere architecture. This LHR version limits hash rate for cryptocurrency mining.",
        'countInStock': 5,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        'id': 4,
        'name': "GeForce RTX 4060 Egle OC 8GB ",
        'images': [
            "/images/4.1.png",
            "/images/4.2.png",
            "/images/4.3.png",
            "/images/4.4.png",
        ],
        'brand': "Gigabyte",
        'price': 432,
        'description': "A future release likely aimed at high 1080p and smooth 1440p gaming with the next-gen NVIDIA Ada Lovelace architecture. This 8GB GDDR6 card boasts the WINDFORCE cooling system for efficient heat dissipation.",
        'countInStock': 2,
        'rating': 3.5,
        'numReviews': 12,
    },
    {
        'id': 5,
        'name': "GeForce RTX 4090 GAMING OC 24GB ",
        'images': [
            "/images/5.1.png",
            "/images/5.2.png",
            "/images/5.3.png",
            "/images/5.4.png",
        ],
        'brand': "Gigabyte",
        'price': 2233,
        'description': "A top-of-the-line option for enthusiasts and 4K gamers. This powerhouse features a massive 24GB of GDDR6 memory and the latest NVIDIA Ada Lovelace architecture for unparalleled performance in demanding games and creative applications.",
        'countInStock': 7,
        'rating': 5,
        'numReviews': 12,
    },
    {
        'id': 6,
        'name': "Radeon RX 7900 XTX NITRO+ Vapor-X 24GB",
        'images': [
            "/images/6.1.png",
            "/images/6.2.png",
            "/images/6.3.png",
            "/images/6.4.png",
        ],
        'brand': "Sapphire",
        'price': 1324,
        'description': "Likely a high-end offering from Sapphire featuring the next-gen AMD RDNA 3 architecture. With 24GB of GDDR6 memory, it's geared towards smooth 4K gaming and potentially 8K readiness.",
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },

]
